# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        avatar:
            quality: 75
            filters:
                thumbnail:
                    size : [50, 50]
                    mode : outbound
        card:
            quality: 75
            filters:
                thumbnail:
                    size : [250, 200]
                    mode : outbound
        big:
            quality: 75
            filters:
                thumbnail:
                    size : [750, 400]

    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"
